[package]
name = "riscv-emu"
version = "0.1.0"
authors = ["kurun"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
memmap = "0.7.0"
pancurses = "0.16.1"

[features]
#default = ["xv6"]
xv6 = []
nuttx = []
